export interface PakistanCity {
  slug: string;
  name: string;
  province: string;
  population: number;
  areaCode?: string;
  lat: number;
  lng: number;
  searchVolumeEstimate: number;
  keywords: string[];
}

export interface PakistanCarrier {
  slug: string;
  name: string;
  shortName: string;
  appName: string;
  appUrl: string;
  ussdCodes: string[];
  keywords: string[];
  color: string;
  logoColor: string;
  franchiseUrl: string;
}

export const PAKISTAN_CITIES: PakistanCity[] = [
  {
    slug: 'karachi',
    name: 'Karachi',
    province: 'Sindh',
    population: 14910352,
    areaCode: '021',
    lat: 24.8607,
    lng: 67.0011,
    searchVolumeEstimate: 8500,
    keywords: [
      'karachi sim owner details',
      'karachi sim number check',
      'karachi cnic sim check',
      'karachi phone number details',
      'karachi mobile number details',
      'jazz sim owner details karachi',
      'zong sim owner details karachi',
      'telenor sim owner details karachi',
      'ufone sim owner details karachi',
      'karachi sim verification',
      'karachi sim details by number',
      'karachi live tracker sim data',
    ],
  },
  {
    slug: 'lahore',
    name: 'Lahore',
    province: 'Punjab',
    population: 11126285,
    areaCode: '042',
    lat: 31.5204,
    lng: 74.3587,
    searchVolumeEstimate: 7200,
    keywords: [
      'lahore sim owner details',
      'lahore sim number check',
      'lahore cnic sim check',
      'lahore phone number details',
      'lahore mobile number details',
      'jazz sim owner details lahore',
      'zong sim owner details lahore',
      'telenor sim owner details lahore',
      'ufone sim owner details lahore',
      'lahore sim verification',
      'lahore sim details by number',
      'lahore live tracker sim data',
    ],
  },
  {
    slug: 'faisalabad',
    name: 'Faisalabad',
    province: 'Punjab',
    population: 3203846,
    areaCode: '041',
    lat: 31.4504,
    lng: 73.135,
    searchVolumeEstimate: 2100,
    keywords: [
      'faisalabad sim owner details',
      'faisalabad sim number check',
      'faisalabad cnic sim check',
      'faisalabad phone number details',
      'faisalabad mobile number details',
      'jazz sim owner details faisalabad',
      'zong sim owner details faisalabad',
      'telenor sim owner details faisalabad',
      'ufone sim owner details faisalabad',
      'faisalabad sim verification',
    ],
  },
  {
    slug: 'rawalpindi',
    name: 'Rawalpindi',
    province: 'Punjab',
    population: 2098231,
    areaCode: '051',
    lat: 33.5973,
    lng: 73.0479,
    searchVolumeEstimate: 1800,
    keywords: [
      'rawalpindi sim owner details',
      'rawalpindi sim number check',
      'rawalpindi cnic sim check',
      'rawalpindi phone number details',
      'rawalpindi mobile number details',
      'jazz sim owner details rawalpindi',
      'zong sim owner details rawalpindi',
      'telenor sim owner details rawalpindi',
      'ufone sim owner details rawalpindi',
      'rawalpindi sim verification',
    ],
  },
  {
    slug: 'multan',
    name: 'Multan',
    province: 'Punjab',
    population: 1871843,
    areaCode: '061',
    lat: 30.1575,
    lng: 71.5249,
    searchVolumeEstimate: 1500,
    keywords: [
      'multan sim owner details',
      'multan sim number check',
      'multan cnic sim check',
      'multan phone number details',
      'multan mobile number details',
      'jazz sim owner details multan',
      'zong sim owner details multan',
      'telenor sim owner details multan',
      'ufone sim owner details multan',
      'multan sim verification',
    ],
  },
  {
    slug: 'hyderabad',
    name: 'Hyderabad',
    province: 'Sindh',
    population: 1732693,
    areaCode: '022',
    lat: 25.3792,
    lng: 68.3683,
    searchVolumeEstimate: 1400,
    keywords: [
      'hyderabad sim owner details',
      'hyderabad sim number check',
      'hyderabad cnic sim check',
      'hyderabad phone number details',
      'hyderabad mobile number details',
      'jazz sim owner details hyderabad',
      'zong sim owner details hyderabad',
      'telenor sim owner details hyderabad',
      'ufone sim owner details hyderabad',
      'hyderabad sim verification',
    ],
  },
  {
    slug: 'gujranwala',
    name: 'Gujranwala',
    province: 'Punjab',
    population: 1627000,
    areaCode: '055',
    lat: 32.1617,
    lng: 74.1883,
    searchVolumeEstimate: 1200,
    keywords: [
      'gujranwala sim owner details',
      'gujranwala sim number check',
      'gujranwala cnic sim check',
      'gujranwala phone number details',
      'gujranwala mobile number details',
      'jazz sim owner details gujranwala',
      'zong sim owner details gujranwala',
      'telenor sim owner details gujranwala',
      'ufone sim owner details gujranwala',
      'gujranwala sim verification',
    ],
  },
  {
    slug: 'peshawar',
    name: 'Peshawar',
    province: 'Khyber Pakhtunkhwa',
    population: 1970042,
    areaCode: '091',
    lat: 34.015,
    lng: 71.5249,
    searchVolumeEstimate: 1800,
    keywords: [
      'peshawar sim owner details',
      'peshawar sim number check',
      'peshawar cnic sim check',
      'peshawar phone number details',
      'peshawar mobile number details',
      'jazz sim owner details peshawar',
      'zong sim owner details peshawar',
      'telenor sim owner details peshawar',
      'ufone sim owner details peshawar',
      'peshawar sim verification',
    ],
  },
  {
    slug: 'quetta',
    name: 'Quetta',
    province: 'Balochistan',
    population: 1001205,
    areaCode: '081',
    lat: 30.1798,
    lng: 66.975,
    searchVolumeEstimate: 900,
    keywords: [
      'quetta sim owner details',
      'quetta sim number check',
      'quetta cnic sim check',
      'quetta phone number details',
      'quetta mobile number details',
      'jazz sim owner details quetta',
      'zong sim owner details quetta',
      'telenor sim owner details quetta',
      'ufone sim owner details quetta',
      'quetta sim verification',
    ],
  },
  {
    slug: 'islamabad',
    name: 'Islamabad',
    province: 'Islamabad Capital Territory',
    population: 1014825,
    areaCode: '051',
    lat: 33.6844,
    lng: 73.0479,
    searchVolumeEstimate: 1600,
    keywords: [
      'islamabad sim owner details',
      'islamabad sim number check',
      'islamabad cnic sim check',
      'islamabad phone number details',
      'islamabad mobile number details',
      'jazz sim owner details islamabad',
      'zong sim owner details islamabad',
      'telenor sim owner details islamabad',
      'ufone sim owner details islamabad',
      'islamabad sim verification',
    ],
  },
  {
    slug: 'sargodha',
    name: 'Sargodha',
    province: 'Punjab',
    population: 659862,
    areaCode: '048',
    lat: 32.0836,
    lng: 72.6711,
    searchVolumeEstimate: 600,
    keywords: [
      'sargodha sim owner details',
      'sargodha sim number check',
      'sargodha cnic sim check',
      'sargodha phone number details',
      'sargodha mobile number details',
      'jazz sim owner details sargodha',
      'zong sim owner details sargodha',
      'telenor sim owner details sargodha',
      'ufone sim owner details sargodha',
      'sargodha sim verification',
    ],
  },
  {
    slug: 'sialkot',
    name: 'Sialkot',
    province: 'Punjab',
    population: 655852,
    areaCode: '052',
    lat: 32.4945,
    lng: 74.5229,
    searchVolumeEstimate: 600,
    keywords: [
      'sialkot sim owner details',
      'sialkot sim number check',
      'sialkot cnic sim check',
      'sialkot phone number details',
      'sialkot mobile number details',
      'jazz sim owner details sialkot',
      'zong sim owner details sialkot',
      'telenor sim owner details sialkot',
      'ufone sim owner details sialkot',
      'sialkot sim verification',
    ],
  },
  {
    slug: 'bahawalpur',
    name: 'Bahawalpur',
    province: 'Punjab',
    population: 762111,
    areaCode: '062',
    lat: 29.3956,
    lng: 71.6722,
    searchVolumeEstimate: 500,
    keywords: [
      'bahawalpur sim owner details',
      'bahawalpur sim number check',
      'bahawalpur cnic sim check',
      'bahawalpur phone number details',
      'bahawalpur mobile number details',
      'jazz sim owner details bahawalpur',
      'zong sim owner details bahawalpur',
      'telenor sim owner details bahawalpur',
      'ufone sim owner details bahawalpur',
      'bahawalpur sim verification',
    ],
  },
  {
    slug: 'sukkur',
    name: 'Sukkur',
    province: 'Sindh',
    population: 499900,
    areaCode: '071',
    lat: 27.7052,
    lng: 68.8574,
    searchVolumeEstimate: 450,
    keywords: [
      'sukkur sim owner details',
      'sukkur sim number check',
      'sukkur cnic sim check',
      'sukkur phone number details',
      'sukkur mobile number details',
      'jazz sim owner details sukkur',
      'zong sim owner details sukkur',
      'telenor sim owner details sukkur',
      'ufone sim owner details sukkur',
      'sukkur sim verification',
    ],
  },
  {
    slug: 'jhang',
    name: 'Jhang',
    province: 'Punjab',
    population: 414131,
    areaCode: '047',
    lat: 31.2696,
    lng: 72.3176,
    searchVolumeEstimate: 400,
    keywords: [
      'jhang sim owner details',
      'jhang sim number check',
      'jhang cnic sim check',
      'jhang phone number details',
      'jhang mobile number details',
      'jazz sim owner details jhang',
      'zong sim owner details jhang',
      'telenor sim owner details jhang',
      'ufone sim owner details jhang',
      'jhang sim verification',
    ],
  },
  {
    slug: 'sheikhupura',
    name: 'Sheikhupura',
    province: 'Punjab',
    population: 473129,
    areaCode: '056',
    lat: 31.7131,
    lng: 73.9783,
    searchVolumeEstimate: 400,
    keywords: [
      'sheikhupura sim owner details',
      'sheikhupura sim number check',
      'sheikhupura cnic sim check',
      'sheikhupura phone number details',
      'sheikhupura mobile number details',
      'jazz sim owner details sheikhupura',
      'zong sim owner details sheikhupura',
      'telenor sim owner details sheikhupura',
      'ufone sim owner details sheikhupura',
      'sheikhupura sim verification',
    ],
  },
  {
    slug: 'gujrat',
    name: 'Gujrat',
    province: 'Punjab',
    population: 390533,
    areaCode: '053',
    lat: 32.574,
    lng: 74.0758,
    searchVolumeEstimate: 350,
    keywords: [
      'gujrat sim owner details',
      'gujrat sim number check',
      'gujrat cnic sim check',
      'gujrat phone number details',
      'gujrat mobile number details',
      'jazz sim owner details gujrat',
      'zong sim owner details gujrat',
      'telenor sim owner details gujrat',
      'ufone sim owner details gujrat',
      'gujrat sim verification',
    ],
  },
  {
    slug: 'mardan',
    name: 'Mardan',
    province: 'Khyber Pakhtunkhwa',
    population: 371923,
    areaCode: '0937',
    lat: 34.1986,
    lng: 72.0463,
    searchVolumeEstimate: 350,
    keywords: [
      'mardan sim owner details',
      'mardan sim number check',
      'mardan cnic sim check',
      'mardan phone number details',
      'mardan mobile number details',
      'jazz sim owner details mardan',
      'zong sim owner details mardan',
      'telenor sim owner details mardan',
      'ufone sim owner details mardan',
      'mardan sim verification',
    ],
  },
  {
    slug: 'kasur',
    name: 'Kasur',
    province: 'Punjab',
    population: 358409,
    areaCode: '049',
    lat: 31.1185,
    lng: 74.4472,
    searchVolumeEstimate: 300,
    keywords: [
      'kasur sim owner details',
      'kasur sim number check',
      'kasur cnic sim check',
      'kasur phone number details',
      'kasur mobile number details',
      'jazz sim owner details kasur',
      'zong sim owner details kasur',
      'telenor sim owner details kasur',
      'ufone sim owner details kasur',
      'kasur sim verification',
    ],
  },
  {
    slug: 'sahiwal',
    name: 'Sahiwal',
    province: 'Punjab',
    population: 389600,
    areaCode: '040',
    lat: 30.6654,
    lng: 73.1067,
    searchVolumeEstimate: 350,
    keywords: [
      'sahiwal sim owner details',
      'sahiwal sim number check',
      'sahiwal cnic sim check',
      'sahiwal phone number details',
      'sahiwal mobile number details',
      'jazz sim owner details sahiwal',
      'zong sim owner details sahiwal',
      'telenor sim owner details sahiwal',
      'ufone sim owner details sahiwal',
      'sahiwal sim verification',
    ],
  },
  {
    slug: 'okara',
    name: 'Okara',
    province: 'Punjab',
    population: 357549,
    areaCode: '044',
    lat: 30.8106,
    lng: 73.4519,
    searchVolumeEstimate: 300,
    keywords: [
      'okara sim owner details',
      'okara sim number check',
      'okara cnic sim check',
      'okara phone number details',
      'okara mobile number details',
      'jazz sim owner details okara',
      'zong sim owner details okara',
      'telenor sim owner details okara',
      'ufone sim owner details okara',
      'okara sim verification',
    ],
  },
  {
    slug: 'mirpur-khas',
    name: 'Mirpur Khas',
    province: 'Sindh',
    population: 233876,
    areaCode: '0233',
    lat: 25.5266,
    lng: 69.0128,
    searchVolumeEstimate: 250,
    keywords: [
      'mirpur-khas sim owner details',
      'mirpur khas sim number check',
      'mirpur khas cnic sim check',
      'mirpur khas phone number details',
      'mirpur khas mobile number details',
      'jazz sim owner details mirpur khas',
      'zong sim owner details mirpur khas',
      'telenor sim owner details mirpur khas',
      'ufone sim owner details mirpur khas',
      'mirpur khas sim verification',
    ],
  },
  {
    slug: 'rahim-yar-khan',
    name: 'Rahim Yar Khan',
    province: 'Punjab',
    population: 420419,
    areaCode: '068',
    lat: 28.4211,
    lng: 70.2951,
    searchVolumeEstimate: 350,
    keywords: [
      'rahim-yar-khan sim owner details',
      'rahim yar khan sim number check',
      'rahim yar khan cnic sim check',
      'rahim yar khan phone number details',
      'rahim yar khan mobile number details',
      'jazz sim owner details rahim yar khan',
      'zong sim owner details rahim yar khan',
      'telenor sim owner details rahim yar khan',
      'ufone sim owner details rahim yar khan',
      'rahim yar khan sim verification',
    ],
  },
];

export const PAKISTAN_CARRIERS: PakistanCarrier[] = [
  {
    slug: 'jazz',
    name: 'Jazz',
    shortName: 'Jazz',
    appName: 'Jazz World',
    appUrl: 'https://play.google.com/store/apps/details?id=com.mobilink.jazzworld',
    ussdCodes: ['*444#', '*111#', '*111*1#'],
    keywords: [
      'jazz sim owner details',
      'jazz sim number check by cnic',
      'jazz sim owner name',
      'jazz sim owner details online',
      'jazz sim verification',
      'jazz sim details by number',
      'jazz world app sim check',
      'jazz sim owner name by number',
      'check jazz sim on cnic',
      'jazz sim information system',
      'jazz number details check',
      'jazz sim owner check online',
      'jazz sim owner details karachi',
      'jazz sim owner details lahore',
      'jazz sim owner details islamabad',
      'jazz sim owner details rawalpindi',
      'jazz sim owner details faisalabad',
      'jazz sim owner details multan',
      'jazz sim owner details peshawar',
      'jazz sim owner details quetta',
    ],
    color: '#FF6B00',
    logoColor: '#FF8C00',
    franchiseUrl: 'https://www.jazz.com.pk/storelocator',
  },
  {
    slug: 'zong',
    name: 'Zong',
    shortName: 'Zong',
    appName: 'Zong Self-Care',
    appUrl: 'https://play.google.com/store/apps/details?id=com.zong.selfcare',
    ussdCodes: ['*310#', '*222#', '*310*1#'],
    keywords: [
      'zong sim owner details',
      'zong sim number check online',
      'zong sim owner name',
      'zong sim owner details online',
      'zong sim verification',
      'zong sim details by number',
      'zong self care app sim check',
      'zong sim owner name by number',
      'check zong sim on cnic',
      'zong sim information system',
      'zong number details check',
      'zong sim owner check online',
      'zong sim owner details karachi',
      'zong sim owner details lahore',
      'zong sim owner details islamabad',
      'zong sim owner details rawalpindi',
      'zong sim owner details faisalabad',
      'zong sim owner details multan',
      'zong sim owner details peshawar',
      'zong sim owner details quetta',
    ],
    color: '#00A651',
    logoColor: '#00C851',
    franchiseUrl: 'https://www.zong.com.pk/stores',
  },
  {
    slug: 'telenor',
    name: 'Telenor',
    shortName: 'Telenor',
    appName: 'My Telenor',
    appUrl: 'https://play.google.com/store/apps/details?id=com.telenor.mytelenor',
    ussdCodes: ['*444#', '*123#', '*1#'],
    keywords: [
      'telenor sim owner details',
      'telenor sim number check online',
      'telenor sim owner name',
      'telenor sim owner details online',
      'telenor esim pakistan',
      'telenor sim verification',
      'telenor sim details by number',
      'telenor sim owner name by number',
      'check telenor sim on cnic',
      'telenor sim information system',
      'telenor number details check',
      'buy telenor esim online pakistan',
      'telenor esim buy online',
      'my telenor app sim check',
      'telenor sim owner details karachi',
      'telenor sim owner details lahore',
      'telenor sim owner details islamabad',
      'telenor sim owner details rawalpindi',
      'telenor sim owner details faisalabad',
      'telenor sim owner details multan',
      'telenor sim owner details peshawar',
      'telenor sim owner details quetta',
    ],
    color: '#0066CC',
    logoColor: '#1E90FF',
    franchiseUrl: 'https://www.telenor.com.pk/stores',
  },
  {
    slug: 'ufone',
    name: 'Ufone',
    shortName: 'Ufone',
    appName: 'Ufone Self-Care',
    appUrl: 'https://play.google.com/store/apps/details?id=com.ufone.selfcare',
    ussdCodes: ['*336#', '*1#', '*780*3#', '*336*1#'],
    keywords: [
      'ufone sim owner details',
      'ufone sim number check',
      'ufone sim owner name',
      'ufone sim owner details online',
      'ufone number check code',
      'ufone number check',
      'ufone sim verification',
      'ufone sim details by number',
      'ufone sim owner name by number',
      'check ufone sim on cnic',
      'ufone sim information system',
      'ufone number details check',
      'ufone self care app sim check',
      'ufone sim owner check online',
      '*336# ufone number check',
      'ufone sim owner details karachi',
      'ufone sim owner details lahore',
      'ufone sim owner details islamabad',
      'ufone sim owner details rawalpindi',
      'ufone sim owner details faisalabad',
      'ufone sim owner details multan',
      'ufone sim owner details peshawar',
      'ufone sim owner details quetta',
    ],
    color: '#7B2D86',
    logoColor: '#9B4DCA',
    franchiseUrl: 'https://www.ufone.com/storelocator',
  },
];

export function getCityBySlug(slug: string): PakistanCity | undefined {
  return PAKISTAN_CITIES.find(city => city.slug === slug);
}

export function getCarrierBySlug(slug: string): PakistanCarrier | undefined {
  return PAKISTAN_CARRIERS.find(carrier => carrier.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return PAKISTAN_CITIES.map(city => city.slug);
}

export function getAllCarrierSlugs(): string[] {
  return PAKISTAN_CARRIERS.map(carrier => carrier.slug);
}

export function getCityCarrierCombinations(): Array<{ citySlug: string; carrierSlug: string }> {
  const combinations: Array<{ citySlug: string; carrierSlug: string }> = [];
  for (const city of PAKISTAN_CITIES) {
    for (const carrier of PAKISTAN_CARRIERS) {
      combinations.push({ citySlug: city.slug, carrierSlug: carrier.slug });
    }
  }
  return combinations;
}